/// <reference types="Cypress" />
import DataEntry from '../../support/pageObjects/DataEntry'
const DEntry = new DataEntry()
const Dataentry = require('../../fixtures/DatEntry.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(Dataentry.Username,
            Dataentry.Password);
     });
    it('Create Assessment ',function() {
        cy.intercept({
            pathname: "/ErudexWebService/rest/admin/curriculum/getCurriculumDetails"
        }).as('Curr-Data')
	    cy.intercept({
            pathname: "/ErudexWebService/rest/userActivity/addPageActivity"
        }).as('PageActivityData')
	    cy.intercept({
            pathname: "/ErudexWebService/rest/question/search"
        }).as('search')
	    cy.intercept({
            pathname: "/ErudexWebService/rest/question/getSelectOptions"
        }).as('autoSelect')
        cy.intercept({
           pathname: "/ErudexWebService/rest/question/save"
        }).as('Save')
        DEntry.getCreateAssessment()
            .click({force: true})
        DEntry.getNameAssessment()
            .type(Dataentry.exmType)
        DEntry.getType()
            .contains(Dataentry.testtype)
        DEntry.getCurriculam()
            .contains(Dataentry.Curriculum)
        DEntry.getGrade()
            .contains(Dataentry.Class)
        DEntry.getSubject()
            .contains(Dataentry.Subject)
        cy.wait('@Curr-Data')
        DEntry.getLevel()
            .contains(Dataentry.Level)
        DEntry.getDuration()
            .clear()
        DEntry.getDuration()
            .type(Dataentry.Duration)
        DEntry.getMarks()
            .clear()
        DEntry.getMarks()
            .type(Dataentry.Marks)
        DEntry.getSelectquestions()
            .click()
        cy.wait('@search')
        DEntry.getChapter()
            .contains(Dataentry.Chapter)
        Cypress.on('uncaught:exception', (err, runnable) => {
            return false
          })
        cy.wait('@search')  
        DEntry.getTopic()
            .contains(Dataentry.Topic)
        cy.wait('@search')      
        DEntry.getDifficulty()
            .contains(Dataentry.Level)
        DEntry.getQstntype()
             .contains(Dataentry.QstType)
        // DEntry.getSkillType()
        //     .contains(Dataentry.Skill)
        DEntry.getPastexam()
            .contains(Dataentry.pastExm)
        DEntry.getExamyear()
            .contains(Dataentry.Year)
        // DEntry.getQstntype()
        //     .contains(Dataentry.QstType)
        DEntry.getDescription()
            .type(Dataentry.content)
        DEntry.getConcept()
            .type(Dataentry.content)
        DEntry.getAddquestion1()
            .click({force: true})
        DEntry.getAddquestion2()
            .click({force: true})
        DEntry.getAddquestion3()
            .click({force: true})
        DEntry.getAddquestion4()
            .click({force: true})
        DEntry.getAddquestion5()
            .click({force: true})
        DEntry.getOK()
            .click()
        // cy.wait(2500)
        DEntry.getDeleteqstn()
            .click()
        DEntry.getSuccess()
            .click()
        DEntry.getAddNew()
            .click()
        cy.wait('@autoSelect')
    })
    it('Add Questions ',function() {
        cy.intercept({
            pathname: "/ErudexWebService/rest/admin/curriculum/getCurriculumDetails"
        }).as('Curr-Data')
        cy.intercept({
           pathname: "/ErudexWebService/rest/question/save"
        }).as('Save')
        // DEntry.getAddCurriculam()
        //     .contains(Dataentry.Curriculum)
        DEntry.getAddGrade()
            .contains(Dataentry.Class)
        // cy.wait(2000)
        DEntry.getAddSubject()
            .contains(Dataentry.Subject)
        // cy.wait(500)
        DEntry.getAddChapter()
            .contains(Dataentry.Chapter)
        // cy.wait(500)
        // cy.wait('@Curr-Data')
        DEntry.getAddTopic()
            .contains(Dataentry.Topic)
        DEntry.getAddDifficulty()
            .contains(Dataentry.Level)
        DEntry.getAddSkillType()
            .contains(Dataentry.Skill)
        DEntry.getAddQstntype()
            .contains(Dataentry.Qstntype)
        Cypress.on('uncaught:exception', (err, runnable) => {
             return false
          })
        DEntry.getNumericDescription()
            .type(Dataentry.discript)
        DEntry.getNumericAns()
            .type(Dataentry.NumVal)
        DEntry.getQstnSolution()
            .click()
        DEntry.getAnswer1()
            .type(Dataentry.Answer1)
        DEntry.getQstnSolution()
            .click()
        DEntry.getQstnHint()
            .click()
        DEntry.getHint1()
            .type(Dataentry.Hint1)
        DEntry.getQstnHint()
            .click()
        DEntry.getPreview()
            .click()
        DEntry.getClose()
            .click()
        DEntry.getSave()
            .click()
        cy.wait('@Save')
        DEntry.getCLOSE()
            .click()
        DEntry.getSaving()
            .click()
    })
    it('Logout', ()=>{
        cy.Logout()
    })    
})    