/// <reference types="Cypress" />
import DataEntry from '../../support/pageObjects/DataEntry'
const DEntry = new DataEntry()
const Dataentry = require('../../fixtures/DatEntry.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(Dataentry.Username,
            Dataentry.Password);
     });
    it('Create Quiz Assessment ',function() {
        DEntry.getCreateAssessment()
          .click({force: true})
        DEntry.getNameAssessment()
          .type(Dataentry.Quiz)
        DEntry.getType1()
          .contains(Dataentry.Testtype)
        DEntry.getCurriculam()
          .contains(Dataentry.Curriculum)
        DEntry.getGrade()
          .contains(Dataentry.Class)
        DEntry.getSubject()
          .contains(Dataentry.Subject)
        DEntry.getLevel()
          .contains(Dataentry.Level)
        DEntry.getDuration()
          .clear()
        DEntry.getDuration()
          .type(Dataentry.Duration)
        DEntry.getMarks()
          .clear()
        DEntry.getMarks()
          .type(Dataentry.Marks)
        DEntry.getChapterQuiz()
          .contains(Dataentry.QzChapter)
        DEntry.getQuizTopic()
          .contains(Dataentry.QzTopic)
        DEntry.getQuizSubTopic()
          .contains(Dataentry.QzSubTopic)
        DEntry.getSelectquestions()
          .click()
        cy.wait(7000)
        DEntry.getChapter()
          .contains(Dataentry.Chapter)
        Cypress.on('uncaught:exception', (err, runnable) => {
            return false
          })
        DEntry.getTopic()
          .contains(Dataentry.Topic)  
        DEntry.getDifficulty()
          .contains(Dataentry.Level)
        DEntry.getSkillType()
          .contains(Dataentry.Skill)
        DEntry.getPastexam()
          .contains(Dataentry.pastExm)
        DEntry.getExamyear()
          .contains(Dataentry.Year)
        DEntry.getQstntype()
          .contains(Dataentry.QstType)
        DEntry.getDescription()
          .type(Dataentry.content)
        DEntry.getConcept()
          .type(Dataentry.content)
        DEntry.getAddquestion1()
          .click({ force: true })
        DEntry.getAddquestion2()
          .click({ force: true })
        DEntry.getAddquestion3()
          .click({ force: true })
        DEntry.getAddquestion4()
          .click({ force: true })
        DEntry.getAddquestion5()
          .click({ force: true })
        DEntry.getOK()
          .click({force:true})
        cy.wait(2500)
        DEntry.getDeleteqstn()
          .click()
        DEntry.getSuccess()
          .click()
        DEntry.getAddNew()
          .click()
    })
    it('Add MCQ Questions ',function() {
        //DEntry.getAddCurriculam()
        //  .contains(Dataentry.Curriculum)
        DEntry.getAddGrade()
          .contains(Dataentry.Class)
        DEntry.getAddSubject()
          .contains(Dataentry.Subject)
        DEntry.getAddChapter()
          .contains(Dataentry.Chapter)
        DEntry.getAddTopic()
          .contains(Dataentry.Topic)
        DEntry.getAddDifficulty()
          .contains(Dataentry.Level)
        DEntry.getAddSkillType()
          .contains(Dataentry.Skill)
        DEntry.getQstntypeAdd1()
          .contains(Dataentry.QstType)
          Cypress.on('uncaught:exception', (err, runnable) => {
               return false
            })
        DEntry.getqstnDescription()
          .clear()    
        DEntry.getqstnDescription()
          .type(Dataentry.discript)  
        DEntry.getMCQDescrip1()
          .type(Dataentry.MCQDescrip)
        DEntry.getMCQDescrip2()
          .type(Dataentry.MCQDescrip)
        DEntry.getMCQDescrip3()
          .type(Dataentry.MCQDescrip)
        DEntry.getMCQDescrip4()
          .type(Dataentry.MCQDescrip)
        DEntry.getRadio()
          .check(Dataentry.RadioAns)  
        DEntry.getPreview()
          .click()
        DEntry.getClose()
          .click()
        DEntry.getSave()
          .click()
        DEntry.getCLOSE()
          .click()
        DEntry.getSaving()
          .click()    
    })
    it('Logout', ()=>{
      cy.Logout()
    })
})