/// <reference types="Cypress" />
import Reports from '../../support/pageObjects/Reports'
const ReportsPage = new Reports()

const cred = require('../../fixtures/Credentials.json')
const reportsData = require('../../fixtures/Report.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(cred.TeacherUserName,
            cred.TeacherPassword);
     }); 
   it('Teacher Student Reports',function() {
        cy.Curriculum()
        ReportsPage.getStudentReports()
            .click({force:true})
        ReportsPage.getClass()
            .contains(reportsData.Class)
        ReportsPage.getName()
            .type(reportsData.Organisation)
        ReportsPage.getSection()
            .contains(reportsData.Section)
        ReportsPage.getPerformance()
            .click()
        ReportsPage.getMonthPerformance()
            .contains(reportsData.MonthPerform) 
        ReportsPage.getSubjects()
            .contains(reportsData.GradeSubj)
        ReportsPage.getChapters()
            .contains(reportsData.gradechapter)
        cy.wait(1000)    
        ReportsPage.getPerformTopic()
            .contains(reportsData.PerformTopic)
                .click({force:true})
        ReportsPage.getActivityTab()
            .click()
        ReportsPage.getAssessTab()
            .click()
        ReportsPage.getAssignTab()
            .click()
    })
    it('Teacher Usage Reports ',function() {  
        ReportsPage.getStudentReports()
            .click({force:true})
        ReportsPage.getClass()
            .contains(reportsData.Class)
        ReportsPage.getName()
            .type(reportsData.Organisation)
        ReportsPage.getSection()
            .contains(reportsData.Section)
        ReportsPage.getUasgeReport()
            .click()
        ReportsPage.getMonthUsage()
            .contains(reportsData.MonthUsage) 
        ReportsPage.getSubjects()
            .contains(reportsData.GradeSubj)
        ReportsPage.getChapters()
            .contains(reportsData.gradechapter)
        cy.wait(1000)    
        ReportsPage.getPerformTopic()
            .contains(reportsData.PerformTopic)
                .click({force:true})
        ReportsPage.getActivityTab()
            .click()
        ReportsPage.getAssessTab()
            .click()
        ReportsPage.getAssignTab()
            .click()
        ReportsPage.getCollaborationTab()
            .click({force: true})
    })
    it('Teacher Comparative Reports ',function() {
        ReportsPage.getStudentReports()
            .click({force:true})
        ReportsPage.getClass()
            .contains(reportsData.Class)
        ReportsPage.getName()
            .type(reportsData.Organisation)
        ReportsPage.getSection()
            .contains(reportsData.Section)
        ReportsPage.getComparativeperf()
            .click()
        ReportsPage.getComparativesubjct()
            .contains(reportsData.Subjects)
        ReportsPage.getComparativeChapter()
            .contains(reportsData.SubjIntro)
        cy.wait(1000)    
        ReportsPage.getComparativetopics()
            .contains(reportsData.PerformTopic)
                .click({force:true})
        ReportsPage.getComparativegrade()
            .contains(reportsData.grade)
        ReportsPage.getCustomdates()
            .contains(reportsData.CustomDate)
        ReportsPage.getActivityTab()
            .click()
        ReportsPage.getAssessTab()
            .click()
        ReportsPage.getAssignTab()
            .click()    
    })  
    it('Teacher Class Reports ',function() {
        ReportsPage.getClsReports()
            .click({force:true})
        ReportsPage.getClsreportGrade()
            .contains(reportsData.Class)
        ReportsPage.getClasSubjct()
            .contains(reportsData.GradeSubj)
        ReportsPage.getClasSection()
            .contains(reportsData.Section)
        ReportsPage.getActivityTab()
            .click()
        ReportsPage.getAssessTab()
            .click()
        ReportsPage.getAssignTab()
            .click()
        //cy.Logout()
    })
    it('Logout', ()=>{
        cy.Logout()
    })    
    
})    