/*
Author: Murali
*/
/// <reference types="Cypress" />
import Teacherobj from '../../support/pageObjects/Teacherobj'
const TeacherOBJ = new Teacherobj()
const Constvarbl = require('../../fixtures/ConstVarbl.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(Constvarbl.TeacherUserName,
            Constvarbl.TeacherPassword);
     }); 
   it('Teacher Student Reports',function() {
        TeacherOBJ.getCurriculam()
            .click()
        TeacherOBJ.getStudentReorts()
            .click({force:true})
        TeacherOBJ.getclassReport()
            .contains(Constvarbl.Class)
        TeacherOBJ.getReportname()
            .type(Constvarbl.Organisation)
        TeacherOBJ.getReportSection()
            .contains(Constvarbl.Section)
        TeacherOBJ.getPerformance()
            .click()
        TeacherOBJ.getMonthPerformance()
            .contains(Constvarbl.MonthPerform) 
        TeacherOBJ.getSubPerfom()
            .contains(Constvarbl.GradeSubj)
        TeacherOBJ.getChapterPerform()
            .contains(Constvarbl.gradechapter)
        cy.wait(1000)    
        TeacherOBJ.getPerformTopic()
            .contains(Constvarbl.PerformTopic)
                .click({force:true})
        TeacherOBJ.getActivityTab()
            .click()
        TeacherOBJ.getAssessTab()
            .click()
        TeacherOBJ.getAssignTab()
            .click()
    })
    it('Teacher Usage Reports ',function() {  
        TeacherOBJ.getStudentReorts()
            .click({force:true})
        TeacherOBJ.getclassReport()
            .contains(Constvarbl.Class)
        TeacherOBJ.getReportname()
            .type(Constvarbl.Organisation)
        TeacherOBJ.getReportSection()
            .contains(Constvarbl.Section)
        TeacherOBJ.getUasgeReport()
            .click()
        TeacherOBJ.getMonthUsage()
            .contains(Constvarbl.MonthUsage) 
        TeacherOBJ.getSubPerfom()
            .contains(Constvarbl.GradeSubj)
        TeacherOBJ.getActivityTab()
            .click()
        TeacherOBJ.getAssessTab()
            .click()
        TeacherOBJ.getAssignTab()
            .click()
        TeacherOBJ.getCollaborationTab()
            .click({force: true})
    })
    it('Teacher Comparative Reports ',function() {
        TeacherOBJ.getStudentReorts()
            .click({force:true})
        TeacherOBJ.getclassReport()
            .contains(Constvarbl.Class)
        TeacherOBJ.getReportname()
            .type(Constvarbl.Organisation)
        TeacherOBJ.getReportSection()
            .contains(Constvarbl.Section)
        TeacherOBJ.getComparativeperf()
            .click()
        TeacherOBJ.getComparativesub()
            .contains(Constvarbl.Subjects)
        TeacherOBJ.getComparativesubChapter()
            .contains(Constvarbl.SubjIntro)
        cy.wait(1000)    
        TeacherOBJ.getComparativetopics()
            .contains(Constvarbl.PerformTopic)
                .click({force:true})
        TeacherOBJ.getComparativegrade()
            .contains(Constvarbl.grade)
        TeacherOBJ.getCustomdates()
            .contains(Constvarbl.CustomDate)
        TeacherOBJ.getActivityTab()
            .click()
        TeacherOBJ.getAssessTab()
            .click()
        TeacherOBJ.getAssignTab()
            .click()    
    })  
    it('Teacher Class Reports ',function() {
        TeacherOBJ.getClasReports()
            .click({force:true})
        TeacherOBJ.getClsreportGrade()
            .contains(Constvarbl.Class)
        TeacherOBJ.getClsreportsub()
            .contains(Constvarbl.PScinece)
        TeacherOBJ.getClsreportsection()
            .contains(Constvarbl.Section)
        TeacherOBJ.getActivityTab()
            .click()
        TeacherOBJ.getAssessTab()
            .click()
        TeacherOBJ.getAssignTab()
            .click()
        cy.Logout()
    })    
    
})    