/*
Author: Murali
*/
/// <reference types="Cypress" />
import Reports from '../../support/pageObjects/Reports'
const report = new Reports()
const reports = require('../../fixtures/Murali/Report.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(reports.TeacherUserName,
            reports.TeacherPassword);
     }); 
   it('Teacher Student Reports',function() {
        cy.Curriculum()
        report.getStudentReports()
            .click({force:true})
        report.getClass()
            .contains(reports.Class)
        report.getName()
            .type(reports.Organisation)
        report.getSection()
            .contains(reports.Section)
        report.getPerformance()
            .click()
        report.getMonthPerformance()
            .contains(reports.MonthPerform) 
        report.getSubjects()
            .contains(reports.GradeSubj)
        report.getChapters()
            .contains(reports.gradechapter)
        cy.wait(1000)    
        report.getPerformTopic()
            .contains(reports.PerformTopic)
                .click({force:true})
        report.getActivityTab()
            .click()
        report.getAssessTab()
            .click()
        report.getAssignTab()
            .click()
    })
    it('Teacher Usage Reports ',function() {  
        report.getStudentReports()
            .click({force:true})
        report.getClass()
            .contains(reports.Class)
        report.getName()
            .type(reports.Organisation)
        report.getSection()
            .contains(reports.Section)
        report.getUasgeReport()
            .click()
        report.getMonthUsage()
            .contains(reports.MonthUsage) 
        report.getSubjects()
            .contains(reports.GradeSubj)
        report.getActivityTab()
            .click()
        report.getAssessTab()
            .click()
        report.getAssignTab()
            .click()
        report.getCollaborationTab()
            .click({force: true})
    })
    it('Teacher Comparative Reports ',function() {
        report.getStudentReports()
            .click({force:true})
        report.getClass()
            .contains(reports.Class)
        report.getName()
            .type(reports.Organisation)
        report.getSection()
            .contains(reports.Section)
        report.getComparativeperf()
            .click()
        report.getComparativesubjct()
            .contains(reports.Subjects)
        report.getComparativeChapter()
            .contains(reports.SubjIntro)
        cy.wait(1000)    
        report.getComparativetopics()
            .contains(reports.PerformTopic)
                .click({force:true})
        report.getComparativegrade()
            .contains(reports.grade)
        report.getCustomdates()
            .contains(reports.CustomDate)
        report.getActivityTab()
            .click()
        report.getAssessTab()
            .click()
        report.getAssignTab()
            .click()    
    })  
    it('Teacher Class Reports ',function() {
        report.getClsReports()
            .click({force:true})
        report.getClsreportGrade()
            .contains(reports.Class)
        report.getClasSubjct()
            .contains(reports.PScinece)
        report.getClasSection()
            .contains(reports.Section)
        report.getActivityTab()
            .click()
        report.getAssessTab()
            .click()
        report.getAssignTab()
            .click()
        cy.Logout()
    })    
    
})    