/// <reference types="Cypress" />
import DataEntry from '../../support/pageObjects/DataEntry'
const DEntry = new DataEntry()
const Dataentry = require('../../fixtures/DatEntry.json')
describe('My First Test Suite', function() 
{
    it('Signin', ()=>{
        cy.Signin(Dataentry.UsrName,
            Dataentry.Paswd);
     });
    it('Create Assessment Use Pre-Made',function() {
        cy.Curriculum()
        DEntry.getCreateAssess()
            .click({force: true})
        DEntry.getAssessmentName()
            .type(Dataentry.name)
        DEntry.getAssessLanguage()
            .contains(Dataentry.Lang)
        DEntry.getAssessClass()
            .contains(Dataentry.Class)
        DEntry.getAssessSubj()
            .contains(Dataentry.Subject)
        DEntry.getAssessDifficulty()
            .contains(Dataentry.Level)
        DEntry.getAssessTime()
            .contains(Dataentry.Duration) 
        DEntry.getAssessMarks()
            .contains(Dataentry.Marks)
        cy.contains(Dataentry.usepremode)
            .click()
        DEntry.getName()
            .type(Dataentry.name)
        DEntry.getAssessLevel()
            .contains(Dataentry.Level)
        DEntry.getOwner()
            .contains(Dataentry.Owner)
        DEntry.getAssessDate()
            .contains(Dataentry.CreatedDate)
        DEntry.getCalender1()
            .click()
        DEntry.getDate()
            .contains(Dataentry.Date1)
                .click()    
        DEntry.getCalender2()
            .click()
        DEntry.getDate()
            .contains(Dataentry.Date1)
                .click()
        DEntry.getSelectButton()
            .click({force:true})
        DEntry.getSelectquestions()
            .click()
        DEntry.getAddquestion3()
            .click({force: true})
        DEntry.getOK()
            .click()
        DEntry.getCreateNdPush()
            .click({force: true})
        DEntry.getCheckbox()
            .check()
                .should('be.checked')
        DEntry.getStartCalender()
            .click()
        DEntry.getActiveDate(Dataentry.pushDate1)
                .click()
        DEntry.getCalenderHour(Dataentry.pushHour1)
                .click()
        DEntry.getCalenderMinute(Dataentry.pushMin1)
                .click()
        DEntry.getEndCalender()
            .click()
        DEntry.getActiveDate(Dataentry.pushDate2)
            .click()
        DEntry.getCalenderHour(Dataentry.pushHour2)
            .click()
        DEntry.getCalenderMinute(Dataentry.pushMin2)
            .click()
        DEntry.getSubmitPush()
            .click()
    })
    it('Logout', ()=>{
        cy.Logout()
    })
})